[package]
name = "update_gfx"
version = "0.1.0"
edition = "2024"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]

[workspace]

[dependencies]
png = "0.18.0"
xflags = "0.3.2"

[dependencies.gfx_sizes]
path = "../../libs/gfx_sizes"

[dependencies.pak]
path = "../../libs/pak"
